# Generated by Django 5.0.1 on 2024-10-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_email_gen_app', '0002_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('job_role', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
